### install REST Client extentions, before use this
### register
POST  https://fireme.vercel.app/api/register
Content-Type: application/json

{
    "name": "andre",
    "email": "andre3@gmail.com",
    "password": "12345",
    "confirm_password": "12345"
}
### login
POST  https://fireme.vercel.app/api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345"
}

### token
GET https://fireme.vercel.app/api/token

### logout
DELETE  https://fireme.vercel.app/api/logout

### users
GET https://fireme.vercel.app/api/users

### NEED AUTH ------------------------------------------------
### current user
GET https://fireme.vercel.app/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im9tVXBzdklBWEpsWUhaZXlrQ3I3IiwibmFtZSI6InRlc3QgYXBpIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY4OTM1OTg3NiwiZXhwIjoxNjg5MzYwNzc2fQ.KTE3tbMfaZiDiPv0rFK4prnXyfqEbM3aS84ieKue9lk

### upload avatar
POST https://fireme.vercel.app/api/user/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im9tVXBzdklBWEpsWUhaZXlrQ3I3IiwibmFtZSI6InRlc3QgYXBpIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY4OTM1OTg3NiwiZXhwIjoxNjg5MzYwNzc2fQ.KTE3tbMfaZiDiPv0rFK4prnXyfqEbM3aS84ieKue9lk

### remove avatar
DELETE https://fireme.vercel.app/api/user/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im9tVXBzdklBWEpsWUhaZXlrQ3I3IiwibmFtZSI6InRlc3QgYXBpIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY4OTM1OTg3NiwiZXhwIjoxNjg5MzYwNzc2fQ.KTE3tbMfaZiDiPv0rFK4prnXyfqEbM3aS84ieKue9lk