### install REST Client extentions, before use this
### stored
POST  http://localhost:5000/api/test/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBxeTNBU2JjRkNIOXVPdUFVRWlwIiwibmFtZSI6ImFuZHJlIiwiZW1haWwiOiJhbmRyZTNAZ21haWwuY29tIiwiaWF0IjoxNjg5NzQ2MjIwLCJleHAiOjE2ODk3NDk4MjB9.7sooBDh146bsryjAJHxGxZl5bHyO0nfiswTIa3y8aKw

{
    "name": "Charger Macbook 3",
    "price":"14000",
    "category_id": "fo5CuYdJmBcJmTiPftZ9" 
}

### fetch
GET http://localhost:5000/api/test/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBxeTNBU2JjRkNIOXVPdUFVRWlwIiwibmFtZSI6ImFuZHJlIiwiZW1haWwiOiJhbmRyZTNAZ21haWwuY29tIiwiaWF0IjoxNjg5NzQ2MjIwLCJleHAiOjE2ODk3NDk4MjB9.7sooBDh146bsryjAJHxGxZl5bHyO0nfiswTIa3y8aKw

### update
PUT http://localhost:5000/api/test/product/NwWR7tFeFrSGL3bXcjZV
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBxeTNBU2JjRkNIOXVPdUFVRWlwIiwibmFtZSI6ImFuZHJlIiwiZW1haWwiOiJhbmRyZTNAZ21haWwuY29tIiwiaWF0IjoxNjg5NzQ2MjIwLCJleHAiOjE2ODk3NDk4MjB9.7sooBDh146bsryjAJHxGxZl5bHyO0nfiswTIa3y8aKw

{
    "name": "Mouse Type A",
    "category_id": "lcSELceuXsKUmAuBfLxH" 
}

### delete
DELETE http://localhost:5000/api/test/product/asdasdas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBxeTNBU2JjRkNIOXVPdUFVRWlwIiwibmFtZSI6ImFuZHJlIiwiZW1haWwiOiJhbmRyZTNAZ21haWwuY29tIiwiaWF0IjoxNjg5NzQ2MjIwLCJleHAiOjE2ODk3NDk4MjB9.7sooBDh146bsryjAJHxGxZl5bHyO0nfiswTIa3y8aKw
