### install REST Client extentions, before use this
### stored
POST  http://localhost:5000/api/product
Content-Type: application/json

{
    "name": "Andre Aipassa",
    "price": 2000
}


### fetch
GET http://localhost:5000/api/product

### fetch one
GET http://localhost:5000/api/product/And

### search
GET http://localhost:5000/api/product/search/Andre

### delete
DELETE http://localhost:5000/api/product/21000

### update
PUT   http://localhost:5000/api/product/Ot3UxjOx7EDVqTxd9tK6
Content-Type: application/json

{
    "name": "Andre Christian Aipassa",
    "price": 7879
}

### update many
PUT   http://localhost:5000/api/product
Content-Type: application/json

{
    "new_price": 1000,
    "old_price": 9000
}

### remove role
DELETE http://localhost:5000/api/product/5fs3hilbpuNxpTddic5F/role

### fetch role
GET http://localhost:5000/api/role