### install REST Client extentions, before use this
### stored
POST  http://localhost:5000/api/product
Content-Type: application/json

{
    "name": "Andr2e",
    "price": 7879
}


### fetch
GET http://localhost:5000/api/product

### fetch one
GET http://localhost:5000/api/product/Andre

### delete
DELETE http://localhost:5000/api/product/es9miuucxR0OuGqTECYI

### update
PUT   http://localhost:5000/api/product/lBJLiL4fzXndD8BXYW3b
Content-Type: application/json

{
    "name": "Aipassa",
    "price": 5000
}

### update many
PUT   http://localhost:5000/api/product
Content-Type: application/json

{
    "new_price": 1000,
    "old_price": 1235
}

