### install REST Client extentions, before use this
### stored
POST  http://localhost:5000/api/product
Content-Type: application/json

{
    "name": "Robert",
    "price": 7880
}


### fetch
GET http://localhost:5000/api/product

### fetch one
GET http://localhost:5000/api/product/Robert

### delete
DELETE http://localhost:5000/api/product/CqveaphkVqUsUQUkzIR9

### update
PUT   http://localhost:5000/api/product/WE9kGVvBbTcR5fZmuuoL
Content-Type: application/json

{
    "name": "Robert beding",
    "price": 5000
}

### update many
PUT   http://localhost:5000/api/product
Content-Type: application/json

{
    "new_price": 1000,
    "old_price": 2000
}



### fetch role
GET http://localhost:5000/api/role