### install REST Client extentions, before use this
### register
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "andre",
    "email": "andre3@gmail.com",
    "password": "12345",
    "confirm_password": "12345"
}
### login
POST  http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "andre3@gmail.com",
    "password": "12345"
}

### token
GET http://localhost:5000/api/token

### logout
DELETE  http://localhost:5000/api/logout

### users
GET http://localhost:5000/api/user

### upload avatar
POST http://localhost:5000/api/user/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5NmpSWGZ5OG5TZlpxazU0NVNOIiwibmFtZSI6ImFuZHJlIiwiZW1haWwiOiJhbmRyZTNAZ21haWwuY29tIiwiaWF0IjoxNjg5MTMyODkxLCJleHAiOjE2ODkxMzM3OTF9.PustdngnknEqrAc1bDla0jDo2s6rEkGPKL9f0RKwvXg