### install REST Client extentions, before use this
### register
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "andre",
    "email": "andre3@gmail.com",
    "password": "12345",
    "confirm_password": "12345"
}
### login
POST  http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "andre3@gmail.com",
    "password": "12345"
}

### token
GET http://localhost:5000/api/token

### logout
DELETE  http://localhost:5000/api/logout

### users
GET http://localhost:5000/api/users

### NEED AUTH ------------------------------------------------
### current user
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBxeTNBU2JjRkNIOXVPdUFVRWlwIiwibmFtZSI6ImFuZHJlIiwiZW1haWwiOiJhbmRyZTNAZ21haWwuY29tIiwiaWF0IjoxNjg5NTYwOTU1LCJleHAiOjE2ODk1NjE4NTV9.AbgajqR5bxz8YrOvF-Kd8QHGyj3XRduiybquiu57If0

### upload avatar
POST http://localhost:5000/api/user/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBxeTNBU2JjRkNIOXVPdUFVRWlwIiwibmFtZSI6ImFuZHJlIiwiZW1haWwiOiJhbmRyZTNAZ21haWwuY29tIiwiaWF0IjoxNjg5NTYwOTU1LCJleHAiOjE2ODk1NjE4NTV9.AbgajqR5bxz8YrOvF-Kd8QHGyj3XRduiybquiu57If0

### remove avatar
DELETE http://localhost:5000/api/user/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlBxeTNBU2JjRkNIOXVPdUFVRWlwIiwibmFtZSI6ImFuZHJlIiwiZW1haWwiOiJhbmRyZTNAZ21haWwuY29tIiwiaWF0IjoxNjg5NTYwOTU1LCJleHAiOjE2ODk1NjE4NTV9.AbgajqR5bxz8YrOvF-Kd8QHGyj3XRduiybquiu57If0