### install REST Client extentions, before use this
### register
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "andre",
    "email": "andre3@gmail.com",
    "password": "12345",
    "confirm_password": "12345"
}
### login
POST  http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "andre3@gmail.com",
    "password": "12345"
}

### token
GET http://localhost:5000/api/token

### logout
DELETE  http://localhost:5000/api/logout
